collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9114899
  brandStrength: 1
  lightness: 0.5223469
  brandColors:
    - '#FEFEFC'
    - '#13181B'
    - '#A2B0B1'
    - '#344147'
    - '#717B72'
  rhythmicContrast: 0.1312464
typography_spectrum: 0.6861476
layout_spectrum: 1
name: cartph
author:
  name: Richie
  url: cartph.com
